/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiModelRouteImport } from './routes/ai-model'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as PatientRouteImport } from './routes/patient'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiModelRoute = AiModelRouteImport.update({
  id: '/ai-model',
  path: '/ai-model',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-model': typeof AiModelRoute
  '/alerts': typeof AlertsRoute
  '/communication': typeof CommunicationRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/patient': typeof PatientRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-model': typeof AiModelRoute
  '/alerts': typeof AlertsRoute
  '/communication': typeof CommunicationRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/patient': typeof PatientRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-model': typeof AiModelRoute
  '/alerts': typeof AlertsRoute
  '/communication': typeof CommunicationRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/patient': typeof PatientRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-model'
    | '/alerts'
    | '/communication'
    | '/dashboard'
    | '/devices'
    | '/patient'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-model'
    | '/alerts'
    | '/communication'
    | '/dashboard'
    | '/devices'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/ai-model'
    | '/alerts'
    | '/communication'
    | '/dashboard'
    | '/devices'
    | '/patient'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiModelRoute: typeof AiModelRoute
  AlertsRoute: typeof AlertsRoute
  CommunicationRoute: typeof CommunicationRoute
  DashboardRoute: typeof DashboardRoute
  DevicesRoute: typeof DevicesRoute
  PatientRoute: typeof PatientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-model': {
      id: '/ai-model'
      path: '/ai-model'
      fullPath: '/ai-model'
      preLoaderRoute: typeof AiModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiModelRoute: AiModelRoute,
  AlertsRoute: AlertsRoute,
  CommunicationRoute: CommunicationRoute,
  DashboardRoute: DashboardRoute,
  DevicesRoute: DevicesRoute,
  PatientRoute: PatientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
